# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - oldrel
  - release
  - devel
  
os:
  - linux
  
dist:
  - xenial
  
matrix:
  allow_failures:
    - r: devel

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
